### ISSUE TITLE
MAJOR BUG: test compare doesn't work as expected

### ISSUE THREAD

**Issue by lillian-gardenia-seabreeze** [lillian-gardenia-seabreeze/sappho#57]
Test compare doesn't work as expected, which is my error, I should've read closer that `PixelArray.compare` uses 1bit masks, thus if you test a GIF which is two frames of two different solid colors, it may say they're exactly alike.

I'll restore the version which @txanatan made.

**Comment by txanatan** [comment]
Oh wow, I didn't realize it uses 1bit masks. My old method was slow as anything but it's guaranteed to work I guess.

We should really test the compare method...

**Comment by lillian-gardenia-seabreeze** [comment]
I implemented a new method, however, I uncovered a super depressing bug in Pygame for OS X, which felt like a steel blade to my heart.

https://bitbucket.org/pygame/pygame/issues/298/bmp-and-png-images-not-loaded-correctly

I'll have to develop on another... operating system... until these issues are resolved. :(

**Comment by lillian-gardenia-seabreeze** [comment]
Okay so this occurs *because* of the difference in pygame being tested with `py.test` and our tests in `tests/`. Namely, that pygame never actually initializes or anything like that in the tests, and as such, that is the only major difference between files saved in test and files saved in demo.

In summation, pygame bug only in tests, not when pygame actually initialized.

**Comment by txanatan** [comment]
Is there a way to have an init function that py.test will run before running the tests?
